# Этап 1: Сборка
FROM node:22 AS build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install --legacy-peer-deps

COPY . .

# Собираем production версию
RUN npm run build -- --configuration=production --base-href=/


EXPOSE 80

# Команда для запуска Angular приложения с использованием ng serve
CMD ["ng", "serve", "--host", "0.0.0.0", "--port", "8020"]
