services:

  frontend:
    container_name: frontend_dorservice
    build:
      context: ./
      dockerfile: Dockerfile-frontend
    ports:
      - 8020:8020
    networks:
      - dorservice
    
  
networks:
  dorservice:
    external: true

    
